[build]
  # Se ELIMINA el comando 'sed'. La clave de API ya no se inyecta en el frontend.
  # command = "sed -i 's|__APP_API_KEY__|'\"$APP_API_KEY\"'|g' public/index.html" <--- ELIMINADO
  publish = "public"
  functions = "netlify/functions"

[dev]
  port = 9999

  # INICIO DE INCLUSIÓN: Aumentar Timeout para funciones lentas

[functions]
  # Aumentar el tiempo de espera para importaciones grandes
  "bulk-import-stock" = {
    timeout = 60 # 60 segundos
  }

# FIN DE INCLUSIÓN